name: Deploy to AWS

on:
  push:
    branches: [ chore/github-actions ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: backend/go.sum

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/OneAI-mini-project
            git pull origin chore/github-actions
            
            # Update and restart scraper
            cd ~/OneAI-mini-project/scraper
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Update and restart backend
            cd ~/OneAI-mini-project/backend
            go mod download
            go build -o api
            sudo systemctl daemon-reload
            sudo systemctl restart oneai-api
            echo "Checking API service status..."
            sudo systemctl status oneai-api --no-pager
